/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.TextEditorPanel;

import java.awt.BorderLayout;
import org.fife.ui.rsyntaxtextarea.*;
import org.fife.ui.rtextarea.*;

/**
 * Clase que se encarga de generar el editor de texto correspodiente para cada
 * uno de los archivos que se abren
 * @author richard
 */
public class WebAssEditor extends javax.swing.JPanel {

    String pathArchivo;

    String fileName;
    /**
     * Construye un nuevo Panel editor de Texto, Usando la libreria: Rsyntax Highlighter
     * @param pathArchivo ruta del archivo
     * @param ext la extension de el archivo
     */
    public WebAssEditor(String pathArchivo) {
        this.pathArchivo = pathArchivo;
        initComponents();
        
        String arr[] = pathArchivo.split("/");
        
        this.fileName  = arr[arr.length - 1];
        
        this.setLayout(new BorderLayout());
        RSyntaxTextArea t = new RSyntaxTextArea();
        t.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        try {
            Theme theme = Theme.load(getClass().getResourceAsStream("/org/fife/ui/rsyntaxtextarea/themes/monokai.xml"));
            theme.apply(t);
        } catch (Exception e) {
        }
     
        
        RTextScrollPane sp = new RTextScrollPane(t);
        this.add(sp);
    }
    
    /**
     * Metodo que devuelve el path del archivo para realizar su lectura
     * @return String, pathArchivo
     */
    public String getPathFile()
    {
        return this.pathArchivo;
    }
    
    /**
     * Metodo que retorna el nombre del archivo
     * @return String, Nombre del archivo
     */
    public String getFileName()
    {
        return this.fileName;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
