/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author richard
 */
public class IDE extends javax.swing.JFrame {
    
    int status = 0;
    /**
     * Creates new form IDE
     */
    public IDE() {
        initComponents();
        
        ImageIcon img = new ImageIcon(this.getClass().getResource("Iconos/coding.png"));
        this.setIconImage(img.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        BotonCrearArchivo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BotonCrearCarpeta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotonAbrirProyecto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BotonGuardarActual = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        BotonCerrarActual = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ButtonRun = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        ButtonDebug = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        EditorTab = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDE Web Assembly");

        jPanel1.setBackground(new java.awt.Color(79, 79, 79));
        jPanel1.setAutoscrolls(true);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        BotonCrearArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/add-file.png"))); // NOI18N
        BotonCrearArchivo.setToolTipText("Nuevo Archivo");
        BotonCrearArchivo.setFocusable(false);
        BotonCrearArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonCrearArchivo.setOpaque(false);
        BotonCrearArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BotonCrearArchivo);
        jToolBar1.add(jSeparator1);

        BotonCrearCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/folder.png"))); // NOI18N
        BotonCrearCarpeta.setToolTipText("Nueva Carpeta");
        BotonCrearCarpeta.setFocusable(false);
        BotonCrearCarpeta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCrearCarpeta.setOpaque(false);
        BotonCrearCarpeta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BotonCrearCarpeta);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/vertical-ellipsis (1).png"))); // NOI18N
        jToolBar1.add(jLabel1);

        BotonAbrirProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/packing.png"))); // NOI18N
        BotonAbrirProyecto.setToolTipText("Abrir Proyecto");
        BotonAbrirProyecto.setFocusable(false);
        BotonAbrirProyecto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonAbrirProyecto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BotonAbrirProyecto);
        jToolBar1.add(jSeparator2);

        BotonGuardarActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/save.png"))); // NOI18N
        BotonGuardarActual.setToolTipText("Guardar Actual");
        BotonGuardarActual.setFocusable(false);
        BotonGuardarActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonGuardarActual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BotonGuardarActual);
        jToolBar1.add(jSeparator3);

        BotonCerrarActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/file.png"))); // NOI18N
        BotonCerrarActual.setToolTipText("Cerrar Pestana Actual");
        BotonCerrarActual.setFocusable(false);
        BotonCerrarActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCerrarActual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BotonCerrarActual);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/vertical-ellipsis (1).png"))); // NOI18N
        jToolBar1.add(jLabel2);

        ButtonRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/movie-player-play-button.png"))); // NOI18N
        ButtonRun.setToolTipText("Compilar");
        ButtonRun.setFocusable(false);
        ButtonRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ButtonRun);
        jToolBar1.add(jSeparator4);

        ButtonDebug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/debug.png"))); // NOI18N
        ButtonDebug.setToolTipText("Debug");
        ButtonDebug.setFocusable(false);
        ButtonDebug.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonDebug.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ButtonDebug);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/vertical-ellipsis (1).png"))); // NOI18N
        jToolBar1.add(jLabel3);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.addTab("Errores", new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/cancel.png")), jScrollPane1); // NOI18N
        jTabbedPane1.addTab("Consola", new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/terminal.png")), jScrollPane2); // NOI18N
        jTabbedPane1.addTab("Tabla de Simbolos", new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/table-grid.png")), jScrollPane3); // NOI18N

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("File Explorer"));

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditorTab)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                    .addComponent(EditorTab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/add-file.png"))); // NOI18N
        jMenuItem1.setText("Nuevo Archivo");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Iconos/folder.png"))); // NOI18N
        jMenuItem2.setText("Nueva Carpeta");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem3.setText("Pruebas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if(status == 1)
        {
            this.jTabbedPane1.setVisible(true);
            status = 0;
        }
        else
        {
            this.jTabbedPane1.setVisible(false);
            status = 1;
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbrirProyecto;
    private javax.swing.JButton BotonCerrarActual;
    private javax.swing.JButton BotonCrearArchivo;
    private javax.swing.JButton BotonCrearCarpeta;
    private javax.swing.JButton BotonGuardarActual;
    private javax.swing.JButton ButtonDebug;
    private javax.swing.JButton ButtonRun;
    private javax.swing.JTabbedPane EditorTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
