
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 15 18:08:05 CST 2018
//----------------------------------------------------

package DracoScriptPackage.Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int romper = 37;
  public static final int dif = 17;
  public static final int mod = 33;
  public static final int ptComa = 2;
  public static final int coma = 6;
  public static final int igual = 16;
  public static final int identificador = 42;
  public static final int caracter = 43;
  public static final int si = 34;
  public static final int mientras = 20;
  public static final int dec = 15;
  public static final int funPoint = 22;
  public static final int menos = 10;
  public static final int menor = 18;
  public static final int var = 38;
  public static final int EOF = 0;
  public static final int funOval = 24;
  public static final int mas = 9;
  public static final int para = 21;
  public static final int error = 1;
  public static final int mayor = 19;
  public static final int runDasm = 30;
  public static final int entero = 40;
  public static final int or = 31;
  public static final int pot = 13;
  public static final int menorigual = 27;
  public static final int funLine = 25;
  public static final int funString = 26;
  public static final int oKey = 7;
  public static final int funQuadrate = 23;
  public static final int falso = 46;
  public static final int cKey = 8;
  public static final int mult = 11;
  public static final int verdad = 45;
  public static final int mayorigual = 28;
  public static final int and = 29;
  public static final int not = 32;
  public static final int asigna = 3;
  public static final int print = 39;
  public static final int inc = 14;
  public static final int div = 12;
  public static final int ifnot = 36;
  public static final int decimal = 41;
  public static final int cadena = 44;
  public static final int sino = 35;
  public static final int oParent = 4;
  public static final int cParent = 5;
}

