
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 03 01:01:09 CST 2018
//----------------------------------------------------

package DracoScriptPackage.Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int romper = 31;
  public static final int dif = 17;
  public static final int mod = 27;
  public static final int ptComa = 2;
  public static final int coma = 6;
  public static final int igual = 16;
  public static final int identificador = 36;
  public static final int caracter = 37;
  public static final int si = 28;
  public static final int mientras = 20;
  public static final int dec = 15;
  public static final int menos = 10;
  public static final int menor = 18;
  public static final int var = 32;
  public static final int EOF = 0;
  public static final int mas = 9;
  public static final int para = 21;
  public static final int error = 1;
  public static final int mayor = 19;
  public static final int entero = 34;
  public static final int or = 25;
  public static final int pot = 13;
  public static final int menorigual = 22;
  public static final int oKey = 7;
  public static final int falso = 40;
  public static final int cKey = 8;
  public static final int mult = 11;
  public static final int verdad = 39;
  public static final int mayorigual = 23;
  public static final int and = 24;
  public static final int not = 26;
  public static final int asigna = 3;
  public static final int print = 33;
  public static final int inc = 14;
  public static final int div = 12;
  public static final int ifnot = 30;
  public static final int decimal = 35;
  public static final int cadena = 38;
  public static final int oParent = 4;
  public static final int cParent = 5;
  public static final int sino = 29;
}

