
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 26 20:08:43 CST 2018
//----------------------------------------------------

package DracoScriptPackage.Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int menorigual = 18;
  public static final int cadena = 28;
  public static final int decimal = 25;
  public static final int not = 22;
  public static final int coma = 6;
  public static final int mult = 9;
  public static final int pot = 11;
  public static final int or = 21;
  public static final int caracter = 27;
  public static final int inc = 12;
  public static final int cParent = 5;
  public static final int menos = 8;
  public static final int menor = 16;
  public static final int mayorigual = 19;
  public static final int div = 10;
  public static final int igual = 14;
  public static final int EOF = 0;
  public static final int dec = 13;
  public static final int error = 1;
  public static final int oParent = 4;
  public static final int ptComa = 2;
  public static final int asigna = 3;
  public static final int entero = 24;
  public static final int mas = 7;
  public static final int dif = 15;
  public static final int mod = 23;
  public static final int and = 20;
  public static final int identificador = 26;
  public static final int mayor = 17;
}

