/* The following code was generated by JFlex 1.4.3 on 10/31/18 10:38 PM */

/*CODIGO DE USUARIO*/
package DasmPackage.Analizador;
import java_cup.runtime.*;
import ErrorManager.TError;
import InfoEstatica.Estatico;
/*OPCIONES Y DECLARACION*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/31/18 10:38 PM from the specification file
 * <tt>lexico.jflex</tt>
 */
public class DasmLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int LINECOMMENT = 4;
  public static final int MULTICOMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\55\1\54\1\0\2\55\22\0\1\55\1\0\1\50\1\0"+
    "\1\3\1\51\4\0\1\7\3\0\1\2\1\6\12\1\7\0\1\10"+
    "\1\30\1\46\1\11\1\23\1\13\1\22\1\4\1\12\2\4\1\16"+
    "\1\14\1\26\1\21\1\53\1\24\1\27\1\4\1\17\1\15\1\20"+
    "\3\4\1\25\4\0\1\5\1\0\1\37\1\41\1\36\1\45\1\32"+
    "\1\52\1\31\1\4\1\44\2\4\1\34\1\4\1\43\1\35\2\4"+
    "\1\47\1\40\1\33\1\42\5\4\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\22\1\1\3\2\4\1\5\1\0"+
    "\3\6\1\7\1\10\6\0\1\11\1\12\1\13\3\0"+
    "\1\14\6\0\1\15\2\6\1\16\1\17\1\0\1\20"+
    "\2\0\1\21\1\22\1\23\1\24\1\25\1\26\11\0"+
    "\1\6\1\27\1\30\1\0\1\31\4\0\1\32\1\33"+
    "\1\34\1\35\1\0\1\36\1\0\1\37\6\0\1\40"+
    "\16\0\1\41\7\0\1\42\1\0\1\43\1\0\1\44"+
    "\1\45\1\46\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284\0\u02b2"+
    "\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398\0\u03c6\0\u03f4\0\212"+
    "\0\212\0\u0422\0\212\0\u0450\0\u047e\0\u04ac\0\u04da\0\212"+
    "\0\212\0\u0508\0\u0536\0\u0564\0\u0592\0\u05c0\0\u05ee\0\u061c"+
    "\0\212\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e"+
    "\0\u078c\0\u07ba\0\u07e8\0\u0816\0\u0450\0\u0844\0\u0872\0\212"+
    "\0\212\0\u08a0\0\212\0\u08ce\0\u08fc\0\212\0\212\0\212"+
    "\0\212\0\212\0\212\0\u092a\0\u0958\0\u0986\0\u09b4\0\u09e2"+
    "\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8\0\u047e\0\212\0\u0af6"+
    "\0\212\0\u0b24\0\u0b52\0\u0b80\0\u0bae\0\212\0\212\0\212"+
    "\0\212\0\u0bdc\0\u047e\0\u0c0a\0\212\0\u0c38\0\u0c66\0\u0c94"+
    "\0\u0cc2\0\u0cf0\0\u0d1e\0\212\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6"+
    "\0\u0e04\0\u0e32\0\u0e60\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18\0\u0f46"+
    "\0\u0f74\0\u0fa2\0\212\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088"+
    "\0\u10b6\0\u10e4\0\212\0\u1112\0\212\0\u1140\0\212\0\212"+
    "\0\212\0\212";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\4\1\6\2\4\1\7\1\4\1\10"+
    "\1\11\1\4\1\12\1\13\1\4\1\14\2\4\1\15"+
    "\1\16\1\17\2\4\1\20\1\4\1\21\1\22\1\4"+
    "\1\23\4\4\1\24\5\4\1\25\1\4\1\26\2\4"+
    "\1\27\2\30\7\31\1\32\44\31\1\30\55\31\1\33"+
    "\1\31\57\0\1\5\1\34\57\0\2\35\2\0\26\35"+
    "\1\36\10\35\1\37\2\0\2\35\10\0\1\40\1\41"+
    "\57\0\1\42\14\0\1\43\41\0\1\44\105\0\1\45"+
    "\30\0\1\46\3\0\1\47\53\0\1\50\65\0\1\51"+
    "\45\0\1\52\62\0\1\53\16\0\1\54\33\0\1\55"+
    "\63\0\1\56\60\0\1\57\55\0\1\60\55\0\1\61"+
    "\62\0\1\62\67\0\1\63\33\0\1\64\34\0\1\33"+
    "\50\0\1\65\55\0\1\35\2\0\2\35\2\0\40\35"+
    "\2\0\2\35\3\0\1\35\2\0\2\35\2\0\27\35"+
    "\1\66\10\35\2\0\2\35\3\0\1\35\2\0\2\35"+
    "\2\0\22\35\1\67\15\35\2\0\2\35\13\0\1\70"+
    "\55\0\1\71\57\0\1\72\4\0\1\73\100\0\1\74"+
    "\30\0\1\75\50\0\1\76\67\0\1\77\55\0\1\100"+
    "\57\0\1\101\75\0\1\102\27\0\1\103\43\0\1\104"+
    "\103\0\1\105\54\0\1\106\56\0\1\107\56\0\1\110"+
    "\57\0\1\111\6\0\1\112\4\0\1\113\15\0\1\114"+
    "\44\0\1\35\2\0\2\35\2\0\24\35\1\115\13\35"+
    "\2\0\2\35\3\0\1\35\2\0\2\35\2\0\23\35"+
    "\1\116\14\35\2\0\2\35\15\0\1\117\100\0\1\120"+
    "\36\0\1\121\50\0\1\122\50\0\1\123\55\0\1\124"+
    "\55\0\1\125\104\0\1\126\71\0\1\127\55\0\1\130"+
    "\55\0\1\131\33\0\1\132\30\0\1\35\2\0\2\35"+
    "\2\0\26\35\1\133\11\35\2\0\2\35\35\0\1\134"+
    "\35\0\1\135\73\0\1\136\2\0\1\137\52\0\1\140"+
    "\2\0\1\141\52\0\1\142\2\0\1\143\40\0\1\144"+
    "\102\0\1\145\45\0\1\146\56\0\1\147\54\0\1\150"+
    "\56\0\1\151\54\0\1\152\56\0\1\153\55\0\1\154"+
    "\55\0\1\155\56\0\1\156\54\0\1\157\56\0\1\160"+
    "\54\0\1\161\56\0\1\162\62\0\1\163\53\0\1\164"+
    "\53\0\1\165\57\0\1\166\53\0\1\167\57\0\1\170"+
    "\53\0\1\171\55\0\1\172\52\0\1\173\60\0\1\174"+
    "\52\0\1\175\60\0\1\176\52\0\1\177\55\0\1\200"+
    "\55\0\1\201\55\0\1\202\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4462];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\23\1\2\11\1\1\1\11\1\0\3\1"+
    "\2\11\6\0\1\1\1\11\1\1\3\0\1\1\6\0"+
    "\3\1\2\11\1\0\1\11\2\0\6\11\11\0\2\1"+
    "\1\11\1\0\1\11\4\0\4\11\1\0\1\1\1\0"+
    "\1\11\6\0\1\11\16\0\1\11\7\0\1\11\1\0"+
    "\1\11\1\0\4\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    String nombreArchivo;
    public void setNombreArchivo(String nombreArchivo)
    {
      this.nombreArchivo = nombreArchivo;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public DasmLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public DasmLex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 24: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.diff, yycolumn, yyline, yytext());
          }
        case 40: break;
        case 6: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.identificador, yycolumn, yyline, yytext());
          }
        case 41: break;
        case 25: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.mult, yycolumn, yyline, yytext());
          }
        case 42: break;
        case 27: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.prChar, yycolumn, yyline, yytext());
          }
        case 43: break;
        case 13: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.decimal, yycolumn, yyline, yytext());
          }
        case 44: break;
        case 36: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.slocal, yycolumn, yyline, yytext());
          }
        case 45: break;
        case 22: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.not, yycolumn, yyline, yytext());
          }
        case 46: break;
        case 33: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.function, yycolumn, yyline, yytext());
          }
        case 47: break;
        case 34: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.glocal, yycolumn, yyline, yytext());
          }
        case 48: break;
        case 28: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.prInt, yycolumn, yyline, yytext());
          }
        case 49: break;
        case 20: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.eqz, yycolumn, yyline, yytext());
          }
        case 50: break;
        case 9: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.lt, yycolumn, yyline, yytext());
          }
        case 51: break;
        case 5: 
          { yybegin(YYINITIAL);
          }
        case 52: break;
        case 2: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.entero, yycolumn, yyline, yytext());
          }
        case 53: break;
        case 15: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.and, yycolumn, yyline, yytext());
          }
        case 54: break;
        case 12: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.br, yycolumn, yyline, yytext());
          }
        case 55: break;
        case 3: 
          { /*NO HAGO NADA*/
          }
        case 56: break;
        case 38: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.tglobal, yycolumn, yyline, yytext());
          }
        case 57: break;
        case 11: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.gt, yycolumn, yyline, yytext());
          }
        case 58: break;
        case 8: 
          { yybegin(MULTICOMMENT);
          }
        case 59: break;
        case 19: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.gte, yycolumn, yyline, yytext());
          }
        case 60: break;
        case 10: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.or, yycolumn, yyline, yytext());
          }
        case 61: break;
        case 32: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.print, yycolumn, yyline, yytext());
          }
        case 62: break;
        case 7: 
          { yybegin(LINECOMMENT);
          }
        case 63: break;
        case 29: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.prFloat, yycolumn, yyline, yytext());
          }
        case 64: break;
        case 18: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.lte, yycolumn,yyline, yytext());
          }
        case 65: break;
        case 14: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.add, yycolumn, yyline, yytext());
          }
        case 66: break;
        case 26: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.llama, yycolumn, yyline, yytext());
          }
        case 67: break;
        case 35: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.tlocal, yycolumn, yyline, yytext());
          }
        case 68: break;
        case 37: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.gglobal, yycolumn, yyline,yytext());
          }
        case 69: break;
        case 17: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.mod, yycolumn, yyline, yytext());
          }
        case 70: break;
        case 31: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.brIf, yycolumn, yyline, yytext());
          }
        case 71: break;
        case 16: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.div, yycolumn, yyline, yytext());
          }
        case 72: break;
        case 30: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.calc, yycolumn, yyline, yytext());
          }
        case 73: break;
        case 4: 
          { /*NO HAY NADA*/
          }
        case 74: break;
        case 1: 
          { TError error = new TError("Caracter: "+yytext(), "Error Lexico, Caracter no reconocido", "Lexico", yyline, yycolumn, false, this.nombreArchivo);
                                                                Estatico.agregarError(error);
          }
        case 75: break;
        case 39: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.sglobal, yycolumn, yyline, yytext());
          }
        case 76: break;
        case 23: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.ret, yycolumn, yyline, yytext());
          }
        case 77: break;
        case 21: 
          { return new Symbol(DasmPackage.Analizador.Simbolos.end, yycolumn, yyline, yytext());
          }
        case 78: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(Simbolos.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
