
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 16 00:35:29 CST 2018
//----------------------------------------------------

package DasmPackage.Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int calc = 25;
  public static final int gglobal = 19;
  public static final int lte = 9;
  public static final int decimal = 33;
  public static final int not = 14;
  public static final int end = 24;
  public static final int tglobal = 22;
  public static final int glocal = 17;
  public static final int mult = 4;
  public static final int function = 23;
  public static final int lt = 7;
  public static final int gte = 10;
  public static final int brIf = 16;
  public static final int or = 13;
  public static final int llama = 31;
  public static final int line = 30;
  public static final int oval = 28;
  public static final int diff = 3;
  public static final int div = 5;
  public static final int add = 2;
  public static final int EOF = 0;
  public static final int gt = 8;
  public static final int str = 29;
  public static final int point = 26;
  public static final int error = 1;
  public static final int eqz = 11;
  public static final int slocal = 18;
  public static final int entero = 32;
  public static final int sglobal = 20;
  public static final int quadrate = 27;
  public static final int tlocal = 21;
  public static final int br = 15;
  public static final int mod = 6;
  public static final int and = 12;
  public static final int identificador = 34;
}

