
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 26 14:09:09 CST 2018
//----------------------------------------------------

package DasmPackage.Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int function = 26;
  public static final int add = 2;
  public static final int mod = 6;
  public static final int slocal = 21;
  public static final int oval = 33;
  public static final int calc = 28;
  public static final int brIf = 16;
  public static final int eqz = 11;
  public static final int gte = 10;
  public static final int gt = 8;
  public static final int prChar = 17;
  public static final int line = 35;
  public static final int identificador = 39;
  public static final int gglobal = 22;
  public static final int sglobal = 23;
  public static final int tglobal = 25;
  public static final int end = 27;
  public static final int quadrate = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int diff = 3;
  public static final int lt = 7;
  public static final int prFloat = 19;
  public static final int entero = 37;
  public static final int prInt = 18;
  public static final int or = 13;
  public static final int lte = 9;
  public static final int ret = 29;
  public static final int tlocal = 24;
  public static final int str = 34;
  public static final int point = 30;
  public static final int mult = 4;
  public static final int and = 12;
  public static final int br = 15;
  public static final int not = 14;
  public static final int print = 31;
  public static final int div = 5;
  public static final int glocal = 20;
  public static final int llama = 36;
  public static final int decimal = 38;
}

