
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 05 19:26:44 CST 2018
//----------------------------------------------------

package DppPackage.Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int continuar = 44;
  public static final int imprimir = 45;
  public static final int numDecimal = 52;
  public static final int ptComa = 2;
  public static final int dataString = 55;
  public static final int detener = 43;
  public static final int nulo = 56;
  public static final int oBracket = 10;
  public static final int coma = 6;
  public static final int igual = 19;
  public static final int identificador = 54;
  public static final int cBracket = 11;
  public static final int caracter = 31;
  public static final int numEntero = 51;
  public static final int si = 40;
  public static final int mientras = 42;
  public static final int ovalo = 49;
  public static final int importar = 35;
  public static final int dec = 18;
  public static final int estructura = 46;
  public static final int menos = 13;
  public static final int menor = 21;
  public static final int EOF = 0;
  public static final int cuadrado = 48;
  public static final int mas = 12;
  public static final int para = 36;
  public static final int verdadero = 33;
  public static final int error = 1;
  public static final int diff = 20;
  public static final int mayor = 22;
  public static final int entero = 28;
  public static final int or = 26;
  public static final int pot = 16;
  public static final int menorigual = 23;
  public static final int punto = 9;
  public static final int vacio = 38;
  public static final int point = 47;
  public static final int oKey = 7;
  public static final int falso = 34;
  public static final int cKey = 8;
  public static final int mult = 14;
  public static final int mayorigual = 24;
  public static final int and = 25;
  public static final int not = 27;
  public static final int linea = 50;
  public static final int booleano = 32;
  public static final int asigna = 3;
  public static final int retornar = 39;
  public static final int inc = 17;
  public static final int div = 15;
  public static final int principal = 37;
  public static final int decimal = 29;
  public static final int dataChar = 53;
  public static final int sino = 41;
  public static final int oParent = 4;
  public static final int cParent = 5;
  public static final int cadena = 30;
}

