
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 17 21:41:21 CST 2018
//----------------------------------------------------

package DppPackage.Analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int numDecimal = 37;
  public static final int ptComa = 2;
  public static final int dataString = 40;
  public static final int coma = 6;
  public static final int igual = 16;
  public static final int identificador = 39;
  public static final int caracter = 28;
  public static final int numEntero = 36;
  public static final int importar = 32;
  public static final int dec = 15;
  public static final int menos = 10;
  public static final int menor = 18;
  public static final int EOF = 0;
  public static final int mas = 9;
  public static final int verdadero = 30;
  public static final int error = 1;
  public static final int diff = 17;
  public static final int mayor = 19;
  public static final int entero = 25;
  public static final int or = 23;
  public static final int pot = 13;
  public static final int menorigual = 20;
  public static final int vacio = 34;
  public static final int oKey = 7;
  public static final int falso = 31;
  public static final int cKey = 8;
  public static final int mult = 11;
  public static final int mayorigual = 21;
  public static final int and = 22;
  public static final int not = 24;
  public static final int booleano = 29;
  public static final int asigna = 3;
  public static final int retornar = 35;
  public static final int inc = 14;
  public static final int div = 12;
  public static final int principal = 33;
  public static final int decimal = 26;
  public static final int dataChar = 38;
  public static final int oParent = 4;
  public static final int cParent = 5;
  public static final int cadena = 27;
}

